### ISSUE TITLE
Followed instructions and nothing happens

### ISSUE THREAD

**Issue by forgettableEgg** [xme/splunk#3]
Whenever I try to run the command I do not see any of my MISP IOC's flow into splunk. I see the command in splunk when I go to advanced search and look under commands but only under its own app. Is there a simple step I may have missed?

**Comment by xme** [comment]
No easy to give any advice based on the information you provided! :(
Is the Authkey correct? The Splunk server can access the MISP servers over HTTPS? (no firewall?)

**Comment by forgettableEgg** [comment]
I needed to put the splunklib library inside the getmispioc app/bin folder which I didn't know until looking at other splunk apps I already had installed. That was pretty much the only issue. Sorry I took a break last night and just figured it out about 10 minutes ago. Now its working great and I love you for making this!

**Comment by xme** [comment]
Glad it works!
